version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./website:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - frontend
      - backend
    depends_on:
      - n8n
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"  # Use environment variable
      POSTGRES_USER: "${DB_USER}"          # Use environment variable
      POSTGRES_DB: "${DB_NAME}"            # Use environment variable
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sh:/docker-entrypoint-initdb.d/01-init-databases.sh
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 3

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY="${N8N_ENCRYPTION_KEY}"  # Use environment variable
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_CORS_ENABLED=true
      - N8N_CORS_ALLOW_ORIGIN="${N8N_CORS_ORIGIN:-http://localhost:8080}"
      - EXECUTIONS_TIMEOUT=600  # 10 minutes
      - EXECUTIONS_TIMEOUT_MAX=3600  # 1 hour
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/custom-nodes:/home/node/.n8n/custom
      - ./n8n/local-files:/files
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -ln | grep 5678"]
      interval: 30s
      timeout: 10s
      retries: 3

  court-processor:
    build:
      context: ./court-processor
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      PYTHONPATH: /app
    volumes:
      - ./court-data/pdfs:/data/pdfs
      - ./court-data/logs:/data/logs
      - ./court-processor:/app
    depends_on:
      - db
    networks:
      - backend
    restart: unless-stopped

  lawyer-chat:
    build: 
      context: ./services/lawyer-chat
      dockerfile: Dockerfile
    container_name: lawyer-chat
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/lawyerchat
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:8080/chat
      - NEXT_PUBLIC_NEXTAUTH_URL=http://localhost:8080/chat
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/c188c31c-1c45-4118-9ece-5b6057ab5177
      - N8N_API_KEY=${N8N_API_KEY}
      - N8N_API_SECRET=${N8N_API_SECRET}
      # Email config
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
    ports:
      - "3001:3000"
    depends_on:
      - db
      - n8n
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://0.0.0.0:3000/chat/api/csrf"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  n8n_data:

networks:
  frontend:
    name: data-compose_frontend
    driver: bridge
  backend:
    name: data-compose_backend
    driver: bridge